### ISSUE TITLE
How to trigger encoding process?

### ISSUE THREAD

**Issue by COLABORATI** [ivebe/lffmpeg#2]
Is there any kind of file/directory watcher that triggers the encoding process? Or does one have to call `Helper::runEncoding(123);` manually?

Thanks again for your attention!

**Comment by ivebe** [comment]
Hello, you need to insert video yourself, and then call `Helper::runEncoding(123);` manually.

**Comment by COLABORATI** [comment]
Thanks for your quick answer, have a nice sunday!
